name: protoc_plugin
version: 0.3.6
author: Dart Team <misc@dartlang.org>
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/dart-protoc-plugin
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
  protobuf: '>=0.3.3 <0.4.0'
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  unittest: any
